# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and tag asset

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
      
    - run: yarn install

    - run: yarn build

    - name: Get short SHA
      uses: benjlevesque/short-sha@v1.2
      
    - name: Get checksum
      run: |
        echo "SHASUM=$(sha256sum ./dist/omnibot.bundle.js | head -c 64)" >> $GITHUB_ENV

    - name: Create release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.SHA }}
        release_name: Build ${{ env.SHA }}
        body: |
          SHA256 checksum of the omnibot.bundle.js: ${{ env.SHASUM }}
    
    - name: Upload release asset
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./dist/omnibot.bundle.js
        asset_name: omnibot.bundle.js
        asset_content_type: applicaiton/javascript
      
